### ISSUE TITLE
JsonSerdeCodec doest exist

### ISSUE THREAD

**Issue by NicTanghe** [Synphonyte/codee#2]
Hello the JsonSerdeCodec For wich I am here does not exist.

**Comment by maccesch** [comment]
It definitely is 😂

https://github.com/Synphonyte/codee/blob/main/src/string/json_serde.rs

You probably didn't enable the `"json_serde"` feature.

```toml

[dependencies]
codee = { version = "0.2", features = ["json_serde"] }
```
